<!DOCTYPE html>
<html lang="ar">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>BKR EDIT</title>
<style>
  body {
    font-family: Arial, sans-serif;
    background: #121212;
    color: #eee;
    margin: 0;
    padding: 20px;
    direction: rtl;
  }
  header {
    text-align: center;
    margin-bottom: 40px;
  }
  h1 {
    font-size: 3em;
    margin: 0;
    color: #00b894;
  }
  .contact {
    text-align: center;
    margin-top: 10px;
    font-size: 1.2em;
    color: #ccc;
  }
  section {
    max-width: 700px;
    margin: auto;
  }
  .service {
    background: #222;
    margin-bottom: 20px;
    padding: 20px;
    border-radius: 10px;
  }
  .service h2 {
    margin-top: 0;
    color: #00cec9;
  }
  .service img {
    max-width: 100%;
    height: auto;
    border-radius: 8px;
  }
  .price {
    margin-top: 10px;
    font-weight: bold;
    color: #55efc4;
  }
</style>
</head>
<body>
<header>
  <h1>BKR EDIT</h1>
  <div class="contact">تابعني على تويتر: <a href="https://twitter.com/000_bkr" target="_blank" style="color:#00b894;">@000_bkr</a></div>
</header>

<section>
  <div class="service">
    <h2>تصوير صور فايف إم</h2>
    <img src="https://cdn.pixabay.com/photo/2017/11/10/05/47/camera-2935037_1280.jpg" alt="تصوير صور فايف إم" />
    <div class="price">السعر يبدأ من 10 دولار للصور القليلة</div>
  </div>

  <div class="service">
    <h2>تصوير فيديو فايف إم</h2>
    <img src="https://cdn.pixabay.com/photo/2016/11/29/10/07/cinema-1869826_1280.jpg" alt="تصوير فيديو فايف إم" />
    <div class="price">السعر يبدأ من 20 دولار للفيديو البسيط</div>
  </div>
</section>
</body>
</html>
